import Foundation
import SwiftUI

@MainActor
final class Localization: ObservableObject {
    @Published var current: String

    init() {
        self.current = UserDefaults.standard.string(forKey: "lume.language") ?? "pt"
    }

    func apply(_ lang: String) {
        current = lang
        UserDefaults.standard.set(lang, forKey: "lume.language")
    }

    func t(_ key: String) -> String {
        let dict = Self.strings[current] ?? Self.strings["pt"]!
        if let val = dict[key] { return val }
        return Self.strings["pt"]?[key] ?? key
    }

    static let availableLanguages: [(code: String, name: String, flag: String)] = [
        ("pt", "Português", "🇧🇷"),
        ("en", "English",   "🇺🇸"),
        ("es", "Español",   "🇪🇸"),
    ]

    private static let strings: [String: [String: String]] = [
        "pt": ptStrings,
        "en": enStrings,
        "es": esStrings,
    ]
}

private let ptStrings: [String: String] = [
    // Sidebar
    "sidebar.dashboard":   "Dashboard",
    "sidebar.memory":      "Memória",
    "sidebar.disk":        "Disco",
    "sidebar.spaceLens":   "Space Lens",
    "sidebar.protection":  "Proteção",
    "sidebar.apps":        "Aplicativos",
    "sidebar.performance": "Performance",
    "sidebar.settings":    "Configurações",
    "sidebar.healthy":     "Sistema saudável",
    "sidebar.health":      "Saúde do Mac",
    "sidebar.health.good": "Boa",
    "sidebar.health.attention": "Atenção",

    // Page headers
    "page.dashboard.title":     "Smart Scan",
    "page.dashboard.subtitle":  "Diagnóstico completo do seu Mac",
    "page.memory.title":        "Memory Cleaner",
    "page.memory.subtitle":     "Libere RAM presa por processos inativos",
    "page.disk.title":          "Disk Cleaner",
    "page.disk.subtitle":       "Remove caches, logs e arquivos desnecessários",
    "page.spaceLens.title":     "Space Lens",
    "page.spaceLens.subtitle":  "Arquivos grandes por disco",
    "page.protection.title":    "Proteção",
    "page.protection.subtitle": "Detecta e remove malware, adware e apps indesejados",
    "page.apps.title":          "Aplicativos",
    "page.apps.subtitle":       "Gerencie e desinstale aplicativos",
    "page.performance.title":   "Performance",
    "page.performance.subtitle":"Otimizações e tarefas de manutenção do sistema",

    // Common buttons / actions
    "common.analyze":   "Analisar",
    "common.analyzing": "Analisando…",
    "common.cancel":    "Cancelar",
    "common.apply":     "Aplicar",
    "common.close":     "Fechar",
    "common.copy":      "Copiar",
    "common.copied":    "Copiado!",
    "common.clean":     "Limpar",
    "common.delete":    "Excluir",
    "common.open":      "Abrir",
    "common.refresh":   "Atualizar",
    "common.loading":   "Carregando…",
    "common.search":    "Buscar…",
    "common.execute":   "Executar",
    "common.running":   "Executando…",
    "common.done":      "Concluído",
    "common.scan":      "Verificar Agora",
    "common.scanning":  "Verificando…",
    "common.rescan":    "Reverificar",
    "common.remove":    "Remover",
    "common.removing":  "Removendo…",
    "common.confirm":   "Confirmar",
    "common.moveToTrash":"Mover para Lixeira",

    // Memory
    "memory.title":        "Limpeza de Memória",
    "memory.subtitle":     "Libere RAM presa em processos inativos",
    "memory.cleanBtn":     "Limpar Memória",
    "memory.cleaning":     "Liberando memória…",
    "memory.success":      "Memória otimizada!",
    "memory.ramUsed":      "RAM em uso",
    "memory.ramFree":      "RAM livre",
    "memory.topProcesses": "Processos com mais consumo",

    // Disk
    "disk.scanBtn":     "Analisar Disco",
    "disk.cleanBtn":    "Limpar Selecionados",
    "disk.junkFound":   "encontrados",
    "disk.cleaning":    "Limpando…",
    "disk.freed":       "liberados!",
    "disk.empty":       "Seu Mac está limpo!",
    "disk.details":     "Ver detalhes",

    // Space Lens
    "spaceLens.allDisks":   "Todos os Discos",
    "spaceLens.minSize":    "Mín:",
    "spaceLens.all":        "Todos",
    "spaceLens.empty":      "Clique em \"Analisar\" para encontrar arquivos grandes",
    "spaceLens.noResults":  "Nenhum arquivo grande encontrado",
    "spaceLens.tryLower":   "Tente diminuir o tamanho mínimo",
    "spaceLens.found":      "itens grandes encontrados",
    "spaceLens.selected":   "selecionados",
    "spaceLens.name":       "Nome",
    "spaceLens.type":       "Tipo",
    "spaceLens.disk":       "Disco",
    "spaceLens.size":       "Tamanho",

    // Protection
    "protection.scanBtn":   "Verificar Agora",
    "protection.scanning":  "Verificando seu Mac…",
    "protection.clean":     "Mac Protegido!",
    "protection.threats":   "Ameaça(s) Encontrada(s)",
    "protection.lastScan":  "Última Verificação",
    "protection.never":     "Nunca",
    "protection.active":    "Ativa",
    "protection.quarantine":"Quarentena",
    "protection.fdaNeeded": "Acesso Completo ao Disco recomendado",
    "protection.fdaWhy":    "Sem essa permissão, a análise será limitada.",
    "protection.fdaBtn":    "Conceder Acesso",
    "protection.threatList":"Ameaças Detectadas",
    "protection.removeSel": "Remover Selecionados",

    // Apps
    "apps.search":       "Buscar apps…",
    "apps.sortBy":       "Ordenar:",
    "apps.sort.name":    "Nome",
    "apps.sort.size":    "Tamanho",
    "apps.sort.lastUsed":"Último uso",
    "apps.count":        "apps",
    "apps.empty":        "Nenhum app encontrado",
    "apps.loading":      "Carregando aplicativos…",
    "apps.remove":       "Remover",
    "apps.app":          "Aplicativo",
    "apps.version":      "Versão",
    "apps.lastUsed":     "Último Uso",
    "apps.size":         "Tamanho",
    "apps.today":        "Hoje",

    // Performance
    "perf.tasksHeader":   "Tarefas de Manutenção",
    "perf.loginItems":    "Itens de Login",
    "perf.launchAgents":  "Launch Agents",
    "perf.loginManage":   "Gerenciar",
    "perf.openSettings":  "Abrir em Ajustes",
    "perf.spotlight":     "Reindexar Spotlight",
    "perf.spotlightDesc": "Resolve problemas de busca lenta",
    "perf.refresh":       "Atualizar lista",
    "perf.loadingItems":  "Carregando itens…",
    "perf.noItems":       "Nenhum item encontrado",
    "perf.enable":        "Ativar",
    "perf.disable":       "Desativar",
    "perf.remove":        "Remover",

    // Settings
    "settings.title":            "Configurações",
    "settings.general":          "Geral",
    "settings.language":         "Idioma",
    "settings.updates":          "Atualizações",
    "settings.donate":           "Doação",
    "settings.behavior":         "Comportamento do App",
    "settings.launchAtLogin":    "Iniciar com o sistema",
    "settings.launchAtLogin.sub":"Lume abre automaticamente ao ligar o Mac",
    "settings.hideFromDock":     "Remover do Dock",
    "settings.hideFromDock.sub": "Mantém Lume apenas na barra de menu superior",
    "settings.language.title":   "Idioma da Interface",
    "settings.language.note":    "Selecione um idioma e clique em \"Aplicar\".",
    "settings.language.apply":   "Aplicar idioma",
    "settings.language.applied": "Idioma aplicado!",
    "settings.donate.header":    "Apoiar o Desenvolvimento",
    "settings.donate.intro":     "Lume é 100% gratuito e sempre será. Se o app te ajudou, considere fazer uma doação.",
    "settings.donate.keyHeader": "Chave de Doador",
    "settings.donate.thanks":    "Muito obrigado pelo apoio!",
    "settings.permissions":      "Permissões do Sistema",
    "settings.perm.fda":         "Acesso Completo ao Disco",
    "settings.perm.fda.sub":     "Necessário para a aba Proteção",
    "settings.perm.granted":     "Concedido",
    "settings.perm.pending":     "Pendente",

    // Menu bar
    "menu.healthy":   "Sistema saudável",
    "menu.openLume":  "Abrir Lume",
    "menu.quitLume":  "Encerrar",
    "menu.diskFree":  "livres no disco",
    "menu.cleanRAM":  "Limpar Memória",
    "menu.quickScan": "Análise Rápida de Lixo",
    "menu.findJunk":  "Encontre arquivos desnecessários",
    "menu.appName":   "Lume for Mac",

    // Dashboard
    "dash.cleanup.title":   "Limpeza Inteligente",
    "dash.cleanup.startScan":"Iniciar Scan",
    "dash.cleanup.intro":   "Clique em \"Iniciar Scan\" para encontrar caches, logs e arquivos desnecessários que estão ocupando espaço no seu Mac.",
    "dash.cleanup.selected":"Selecionado para remoção",
    "dash.cleanup.newScan": "Novo scan",
    "dash.cleanup.cleanNow":"Limpar Agora",

    // Disk
    "disk.total":          "Total",
    "disk.categories":     "Categorias de Junk",
    "disk.empty.click":    "Clique em \"Analisar\" para encontrar arquivos desnecessários",
    "disk.selected":       "Selecionado",
    "disk.recommended":    "Recomendado",
    "disk.recommendedDesc":"Podemos remover com segurança até %@. Não irá afetar o funcionamento do seu Mac.",
    "disk.details.title":  "Detalhes dos Arquivos",
    "disk.details.sub":    "Arquivos que serão removidos por categoria",
    "disk.cat.systemCache":    "Cache do Sistema",
    "disk.cat.logs":           "Logs",
    "disk.cat.temp":           "Arquivos Temporários",
    "disk.cat.oldDownloads":   "Downloads com +30 dias",
    "disk.cat.orphanedSupport":"Restos de Apps Desinstalados",
    "disk.cat.trash":          "Lixeira",
    "disk.cat.xcodeSims":      "Simuladores Xcode",
    "disk.status.idle":     "Pronto para analisar",
    "disk.status.scanning": "Analisando disco…",
    "disk.status.found":    "%@ de junk encontrados",
    "disk.status.clean":    "Seu Mac está limpo!",
    "disk.status.freed":    "✓ %@ liberados!",
    "disk.status.nothing":  "Nada foi removido.",

    // Space Lens (extras)
    "spaceLens.scanning":  "Analisando arquivos…",
    "spaceLens.minHint":   "Tente diminuir o tamanho mínimo (atualmente %d MB)",
    "spaceLens.moveTo":    "Mover %d p/ Lixeira",
    "spaceLens.confirm":   "Isso moverá %d arquivo(s) para a Lixeira. Você poderá restaurá-los se necessário.",
    "spaceLens.kind.folder":   "Pasta",
    "spaceLens.kind.video":    "Vídeo",
    "spaceLens.kind.image":    "Imagem",
    "spaceLens.kind.archive":  "Comprimido",
    "spaceLens.kind.document": "Documento",
    "spaceLens.kind.app":      "Aplicativo",
    "spaceLens.kind.other":    "Outro",

    // Memory (extras)
    "memory.usedOf":     "de %@ usados",
    "memory.detail":     "Uso Detalhado",
    "memory.history":    "Histórico de RAM (2 min)",
    "memory.topMem":     "Processos por Memória",
    "memory.process":    "Processo",
    "memory.pid":        "PID",
    "memory.ram":        "RAM",

    // System Monitor
    "sysmon.cpu": "CPU",
    "sysmon.ram": "RAM",

    // Protection (extras)
    "protection.scanningText":  "Verificando seu Mac…",
    "protection.dbUpdated":     "Base de dados atualizada",
    "protection.coverage":      "Varredura em LaunchAgents, Daemons, Applications e extensões de Chrome/Firefox",
    "protection.macClean":      "Seu Mac está limpo!",
    "protection.noThreats":     "Nenhum malware, adware ou app indesejado foi encontrado.",
    "protection.threat.adware":      "Adware",
    "protection.threat.pup":         "App Indesejado",
    "protection.threat.malware":     "Malware",
    "protection.threat.launchAgent": "Launch Agent Suspeito",
    "protection.threat.extension":   "Extensão Suspeita",
    "protection.confirmTitle":  "Remover Selecionados?",
    "protection.confirmMsg":    "Isso moverá %d ameaça(s) para a Lixeira.",
    "protection.threat.adware.desc":     "Injeta anúncios e altera configurações do navegador",
    "protection.threat.malware.desc":    "Trojans e spyware conhecidos no macOS",
    "protection.threat.pup.desc":        "Programas que exibem alertas falsos",
    "protection.threat.extension.desc":  "Extensões de navegador com comportamento suspeito",
    "protection.threat.pup.short":       "Apps Indesejados",
    "protection.threat.extension.short": "Extensões Suspeitas",

    // Apps (extras)
    "apps.confirmTitle": "Desinstalar aplicativos?",
    "apps.confirmMsg":   "Isso moverá %d app(s) (%@) e seus arquivos de suporte para a Lixeira.",
    "apps.removing":     "Removendo…",
    "apps.removeCount":  "Remover %d (%@)",
    "apps.openInFinder": "Mostrar no Finder",

    // Performance (extras)
    "perf.spotlight.title":       "Spotlight Reindex",
    "perf.spotlight.desc":        "Reconstrói índice de busca do sistema",
    "perf.spotlight.help":        "Útil quando o Spotlight retorna resultados incorretos ou incompletos. O processo leva alguns minutos.",
    "perf.spotlight.btn":         "Reindexar Spotlight",
    "perf.spotlight.running":     "Reindexando…",
    "perf.spotlight.success":     "✓ Reindex iniciado! O processo leva alguns minutos.",
    "perf.spotlight.failure":     "⚠ Não foi possível reindexar. Tente pelo Terminal: sudo mdutil -E /",
    "perf.task.dnsCache.name":    "Limpar DNS Cache",
    "perf.task.dnsCache.desc":    "Resolve problemas de DNS lento",
    "perf.task.permissions.name":"Reparar Permissões",
    "perf.task.permissions.desc":"Corrige permissões do diretório home",
    "perf.task.fontCache.name":  "Limpar Font Cache",
    "perf.task.fontCache.desc":  "Remove cache de fontes corrompidas",
    "perf.task.trash.name":      "Esvaziar Lixeira",
    "perf.task.trash.desc":      "Remove definitivamente arquivos da lixeira",

    // Settings — Donate
    "settings.donate.copy":      "Copiar",
    "settings.donate.copied":    "Copiado para a área de transferência!",
    "settings.donate.pix":       "Brasil",
    "settings.donate.paypal":    "Internacional",
    "settings.donate.keyRandom":"Chave aleatória",
    "settings.donate.keyEmail":  "E-mail",
    "settings.donate.confirmed":"Doação confirmada!",
    "settings.donate.confirmedSub":"Lembretes de doação desativados. Obrigado!",
    "settings.donate.keyIntro": "Após fazer uma doação, envie o comprovante para hasen.borges@gmail.com. Você receberá uma chave exclusiva para desativar os lembretes de doação.",
    "settings.donate.keySuccess":"Chave válida! Obrigado pelo apoio!",
    "settings.donate.validate": "Validar",
    "settings.donate.invalid":  "Chave inválida. Verifique e tente novamente.",
    "settings.donate.placeholder":"Cole sua chave aqui…",

    // Settings — Updates
    "settings.updates.header":   "Informações do Software",
    "settings.updates.compat":   "Compatível com Intel e Apple Silicon",
    "settings.updates.upToDate":"Atualizado",
    "settings.updates.check":    "Verificar Atualizações",
    "settings.updates.note":     "Atualizações automáticas via Sparkle estarão disponíveis em breve. Por enquanto, verifique manualmente.",

    // Settings — General permissions
    "settings.perm.openPrivacy":"Abrir Privacidade & Segurança",
    "settings.perm.fda.full":   "Necessário para a aba Proteção e análise completa do sistema",
    "settings.perm.fda.coverage":"Esta única permissão cobre Desktop, Documentos, Downloads, Música, Imagens, Filmes e os arquivos do sistema usados pela Proteção. Você não precisará aprovar cada pasta individualmente.",
    "settings.perm.manualOverride":     "Marcar como concedido manualmente",
    "settings.perm.manualOverride.sub": "Use isso se você já concedeu Acesso Completo ao Disco no System Settings mas o Lume não reconhece (acontece em apps sem assinatura de desenvolvedor).",
    "settings.maint.title":      "Modo Manutenção",
    "settings.maint.locked":     "Bloqueado. A senha de administrador será solicitada na primeira tarefa que precisar de permissão.",
    "settings.maint.unlocked":   "Desbloqueado. Você não precisará digitar a senha de administrador novamente nesta sessão.",
    "settings.maint.unlock":     "Desbloquear",
    "settings.maint.lock":       "Bloquear",
    "settings.perm.desktop":    "Pasta Desktop",
    "settings.perm.documents":  "Pasta Documentos",
    "settings.perm.downloads":  "Pasta Downloads",
    "settings.perm.spaceLens.sub":"Necessário para Space Lens",
    "settings.general.info":    "Ao remover do Dock, o app fica acessível apenas pelo ícone na barra de menu. Para reabrir a janela principal, clique no ícone.",
    "settings.language.applyHint":"As mudanças de idioma entrarão em vigor imediatamente.",

    // Donation popup
    "donate.popup.title":     "Apoie o Lume for Mac",
    "donate.popup.tagline":   "100% gratuito — mas sua ajuda faz diferença",
    "donate.popup.intro":     "O Lume é desenvolvido por uma pessoa só, com dedicação e carinho. Se ele te ajudou a liberar espaço ou deixar o Mac mais rápido, considere fazer uma doação — qualquer valor ajuda muito!",
    "donate.popup.keyTitle":  "Inserir chave de doador",
    "donate.popup.keyIntro":  "Após doar, envie o comprovante para hasen.borges@gmail.com. Você receberá uma chave para desativar permanentemente este lembrete.",
    "donate.popup.keySuccess":"Chave válida! Lembretes desativados. Obrigado!",
    "donate.popup.validate":  "Validar",
    "donate.popup.invalid":   "Chave inválida. Verifique e tente novamente.",
    "donate.popup.placeholder":"Cole a chave aqui…",
    "donate.popup.alreadyDonated":"Já doei",
    "donate.popup.hide":      "Ocultar",
    "donate.popup.remindLater":"Lembrar depois",
    "donate.popup.support":   "Quero Apoiar!",
    "donate.popup.copied":    "Copiado!",
    "donate.popup.copy":      "Copiar",
]

private let enStrings: [String: String] = [
    "sidebar.dashboard":   "Dashboard",
    "sidebar.memory":      "Memory",
    "sidebar.disk":        "Disk",
    "sidebar.spaceLens":   "Space Lens",
    "sidebar.protection":  "Protection",
    "sidebar.apps":        "Applications",
    "sidebar.performance": "Performance",
    "sidebar.settings":    "Settings",
    "sidebar.healthy":     "System healthy",
    "sidebar.health":      "Mac Health",
    "sidebar.health.good": "Good",
    "sidebar.health.attention": "Attention",

    "page.dashboard.title":     "Smart Scan",
    "page.dashboard.subtitle":  "Complete diagnostic of your Mac",
    "page.memory.title":        "Memory Cleaner",
    "page.memory.subtitle":     "Free up RAM held by inactive processes",
    "page.disk.title":          "Disk Cleaner",
    "page.disk.subtitle":       "Remove caches, logs and unnecessary files",
    "page.spaceLens.title":     "Space Lens",
    "page.spaceLens.subtitle":  "Large files by disk",
    "page.protection.title":    "Protection",
    "page.protection.subtitle": "Detect and remove malware, adware and unwanted apps",
    "page.apps.title":          "Applications",
    "page.apps.subtitle":       "Manage and uninstall apps",
    "page.performance.title":   "Performance",
    "page.performance.subtitle":"System optimizations and maintenance tasks",

    "common.analyze":   "Analyze",
    "common.analyzing": "Analyzing…",
    "common.cancel":    "Cancel",
    "common.apply":     "Apply",
    "common.close":     "Close",
    "common.copy":      "Copy",
    "common.copied":    "Copied!",
    "common.clean":     "Clean",
    "common.delete":    "Delete",
    "common.open":      "Open",
    "common.refresh":   "Refresh",
    "common.loading":   "Loading…",
    "common.search":    "Search…",
    "common.execute":   "Run",
    "common.running":   "Running…",
    "common.done":      "Done",
    "common.scan":      "Scan Now",
    "common.scanning":  "Scanning…",
    "common.checking":  "Checking…",
    "common.rescan":    "Re-scan",
    "common.remove":    "Remove",
    "common.removing":  "Removing…",
    "common.confirm":   "Confirm",
    "common.moveToTrash":"Move to Trash",

    "memory.title":        "Memory Cleanup",
    "memory.subtitle":     "Free RAM held by inactive processes",
    "memory.cleanBtn":     "Free Memory",
    "memory.cleaning":     "Freeing memory…",
    "memory.success":      "Memory optimized!",
    "memory.ramUsed":      "RAM in use",
    "memory.ramFree":      "RAM free",
    "memory.topProcesses": "Top memory-consuming processes",

    "disk.scanBtn":     "Scan Disk",
    "disk.cleanBtn":    "Clean Selected",
    "disk.junkFound":   "found",
    "disk.cleaning":    "Cleaning…",
    "disk.freed":       "freed!",
    "disk.empty":       "Your Mac is clean!",
    "disk.details":     "View details",

    "spaceLens.allDisks":   "All Disks",
    "spaceLens.minSize":    "Min:",
    "spaceLens.all":        "All",
    "spaceLens.empty":      "Click \"Analyze\" to find large files",
    "spaceLens.noResults":  "No large files found",
    "spaceLens.tryLower":   "Try lowering the minimum size",
    "spaceLens.found":      "large items found",
    "spaceLens.selected":   "selected",
    "spaceLens.name":       "Name",
    "spaceLens.type":       "Type",
    "spaceLens.disk":       "Disk",
    "spaceLens.size":       "Size",

    "protection.scanBtn":   "Scan Now",
    "protection.scanning":  "Scanning your Mac…",
    "protection.clean":     "Mac is Protected!",
    "protection.threats":   "Threat(s) Found",
    "protection.lastScan":  "Last Scan",
    "protection.never":     "Never",
    "protection.active":    "Active",
    "protection.quarantine":"Quarantine",
    "protection.fdaNeeded": "Full Disk Access recommended",
    "protection.fdaWhy":    "Without this permission the scan will be limited.",
    "protection.fdaBtn":    "Grant Access",
    "protection.threatList":"Detected Threats",
    "protection.removeSel": "Remove Selected",

    "apps.search":       "Search apps…",
    "apps.sortBy":       "Sort by:",
    "apps.sort.name":    "Name",
    "apps.sort.size":    "Size",
    "apps.sort.lastUsed":"Last used",
    "apps.count":        "apps",
    "apps.empty":        "No apps found",
    "apps.loading":      "Loading apps…",
    "apps.remove":       "Remove",
    "apps.app":          "Application",
    "apps.version":      "Version",
    "apps.lastUsed":     "Last Used",
    "apps.size":         "Size",
    "apps.today":        "Today",

    "perf.tasksHeader":   "Maintenance Tasks",
    "perf.loginItems":    "Login Items",
    "perf.launchAgents":  "Launch Agents",
    "perf.loginManage":   "Manage",
    "perf.openSettings":  "Open in System Settings",
    "perf.spotlight":     "Reindex Spotlight",
    "perf.spotlightDesc": "Fixes slow search issues",
    "perf.refresh":       "Refresh list",
    "perf.loadingItems":  "Loading items…",
    "perf.noItems":       "No items found",
    "perf.enable":        "Enable",
    "perf.disable":       "Disable",
    "perf.remove":        "Remove",

    "settings.title":            "Settings",
    "settings.general":          "General",
    "settings.language":         "Language",
    "settings.updates":          "Updates",
    "settings.donate":           "Donate",
    "settings.behavior":         "App Behavior",
    "settings.launchAtLogin":    "Launch at login",
    "settings.launchAtLogin.sub":"Lume opens automatically when you start your Mac",
    "settings.hideFromDock":     "Hide from Dock",
    "settings.hideFromDock.sub": "Keep Lume only in the top menu bar",
    "settings.language.title":   "Interface Language",
    "settings.language.note":    "Select a language and click \"Apply\".",
    "settings.language.apply":   "Apply language",
    "settings.language.applied": "Language applied!",
    "settings.donate.header":    "Support Development",
    "settings.donate.intro":     "Lume is 100% free and always will be. If it helped you, consider donating.",
    "settings.donate.keyHeader": "Donor Key",
    "settings.donate.thanks":    "Thank you so much for your support!",
    "settings.permissions":      "System Permissions",
    "settings.perm.fda":         "Full Disk Access",
    "settings.perm.fda.sub":     "Required for the Protection tab",
    "settings.perm.granted":     "Granted",
    "settings.perm.pending":     "Pending",

    "menu.healthy":   "System healthy",
    "menu.openLume":  "Open Lume",
    "menu.quitLume":  "Quit",
    "menu.diskFree":  "free on disk",
    "menu.cleanRAM":  "Clean Memory",
    "menu.quickScan": "Quick Junk Scan",
    "menu.findJunk":  "Find unnecessary files",
    "menu.appName":   "Lume for Mac",

    "dash.cleanup.title":   "Smart Cleanup",
    "dash.cleanup.startScan":"Start Scan",
    "dash.cleanup.intro":   "Click \"Start Scan\" to find caches, logs and unnecessary files taking up space on your Mac.",
    "dash.cleanup.selected":"Selected for removal",
    "dash.cleanup.newScan": "New scan",
    "dash.cleanup.cleanNow":"Clean Now",

    "disk.total":          "Total",
    "disk.categories":     "Junk Categories",
    "disk.empty.click":    "Click \"Analyze\" to find unnecessary files",
    "disk.selected":       "Selected",
    "disk.recommended":    "Recommended",
    "disk.recommendedDesc":"We can safely remove up to %@. Won't affect your Mac's functioning.",
    "disk.details.title":  "File Details",
    "disk.details.sub":    "Files to be removed per category",
    "disk.cat.systemCache":    "System Cache",
    "disk.cat.logs":           "Logs",
    "disk.cat.temp":           "Temporary Files",
    "disk.cat.oldDownloads":   "Downloads older than 30 days",
    "disk.cat.orphanedSupport":"Uninstalled Apps Leftovers",
    "disk.cat.trash":          "Trash",
    "disk.cat.xcodeSims":      "Xcode Simulators",
    "disk.status.idle":     "Ready to scan",
    "disk.status.scanning": "Scanning disk…",
    "disk.status.found":    "%@ of junk found",
    "disk.status.clean":    "Your Mac is clean!",
    "disk.status.freed":    "✓ %@ freed!",
    "disk.status.nothing":  "Nothing was removed.",

    "spaceLens.scanning":  "Analyzing files…",
    "spaceLens.minHint":   "Try lowering the minimum size (currently %d MB)",
    "spaceLens.moveTo":    "Move %d to Trash",
    "spaceLens.confirm":   "This will move %d file(s) to the Trash. You can restore them if needed.",
    "spaceLens.kind.folder":   "Folder",
    "spaceLens.kind.video":    "Video",
    "spaceLens.kind.image":    "Image",
    "spaceLens.kind.archive":  "Archive",
    "spaceLens.kind.document": "Document",
    "spaceLens.kind.app":      "App",
    "spaceLens.kind.other":    "Other",

    "memory.usedOf":     "of %@ used",
    "memory.detail":     "Detailed Usage",
    "memory.history":    "RAM History (2 min)",
    "memory.topMem":     "Top Memory Processes",
    "memory.process":    "Process",
    "memory.pid":        "PID",
    "memory.ram":        "RAM",

    "sysmon.cpu": "CPU",
    "sysmon.ram": "RAM",

    "protection.scanningText":  "Scanning your Mac…",
    "protection.dbUpdated":     "Database up to date",
    "protection.coverage":      "Scans LaunchAgents, Daemons, Applications and Chrome/Firefox extensions",
    "protection.macClean":      "Your Mac is clean!",
    "protection.noThreats":     "No malware, adware or unwanted apps were found.",
    "protection.threat.adware":      "Adware",
    "protection.threat.pup":         "Unwanted App",
    "protection.threat.malware":     "Malware",
    "protection.threat.launchAgent": "Suspicious Launch Agent",
    "protection.threat.extension":   "Suspicious Extension",
    "protection.confirmTitle":  "Remove Selected?",
    "protection.confirmMsg":    "This will move %d threat(s) to the Trash.",
    "protection.threat.adware.desc":     "Injects ads and alters browser settings",
    "protection.threat.malware.desc":    "Known macOS trojans and spyware",
    "protection.threat.pup.desc":        "Programs that show fake alerts",
    "protection.threat.extension.desc":  "Browser extensions with suspicious behavior",
    "protection.threat.pup.short":       "Unwanted Apps",
    "protection.threat.extension.short": "Suspicious Extensions",

    "apps.confirmTitle": "Uninstall applications?",
    "apps.confirmMsg":   "This will move %d app(s) (%@) and their support files to the Trash.",
    "apps.removing":     "Removing…",
    "apps.removeCount":  "Remove %d (%@)",
    "apps.openInFinder": "Show in Finder",

    "perf.spotlight.title":       "Spotlight Reindex",
    "perf.spotlight.desc":        "Rebuild the system search index",
    "perf.spotlight.help":        "Useful when Spotlight returns incorrect or incomplete results. The process takes a few minutes.",
    "perf.spotlight.btn":         "Reindex Spotlight",
    "perf.spotlight.running":     "Reindexing…",
    "perf.spotlight.success":     "✓ Reindex started! It takes a few minutes.",
    "perf.spotlight.failure":     "⚠ Reindex failed. Try via Terminal: sudo mdutil -E /",
    "perf.task.dnsCache.name":    "Flush DNS Cache",
    "perf.task.dnsCache.desc":    "Fix slow DNS issues",
    "perf.task.permissions.name":"Repair Permissions",
    "perf.task.permissions.desc":"Fix home directory permissions",
    "perf.task.fontCache.name":  "Clear Font Cache",
    "perf.task.fontCache.desc":  "Remove corrupted font cache",
    "perf.task.trash.name":      "Empty Trash",
    "perf.task.trash.desc":      "Permanently delete files in the trash",

    "settings.donate.copy":      "Copy",
    "settings.donate.copied":    "Copied to clipboard!",
    "settings.donate.pix":       "Brazil",
    "settings.donate.paypal":    "International",
    "settings.donate.keyRandom":"Random key",
    "settings.donate.keyEmail":  "Email",
    "settings.donate.confirmed":"Donation confirmed!",
    "settings.donate.confirmedSub":"Donation reminders disabled. Thank you!",
    "settings.donate.keyIntro": "After donating, send proof to hasen.borges@gmail.com. You will receive a unique key to disable donation reminders.",
    "settings.donate.keySuccess":"Valid key! Thank you for your support!",
    "settings.donate.validate": "Validate",
    "settings.donate.invalid":  "Invalid key. Check and try again.",
    "settings.donate.placeholder":"Paste your key here…",

    "settings.updates.header":   "Software Information",
    "settings.updates.compat":   "Compatible with Intel and Apple Silicon",
    "settings.updates.upToDate":"Up to date",
    "settings.updates.check":    "Check for Updates",
    "settings.updates.note":     "Automatic updates via Sparkle coming soon. For now, check manually.",

    "settings.perm.openPrivacy":"Open Privacy & Security",
    "settings.perm.fda.full":   "Required for the Protection tab and full system analysis",
    "settings.perm.fda.coverage":"This single permission covers Desktop, Documents, Downloads, Music, Pictures, Movies and the system files used by Protection. You won't need to approve each folder individually.",
    "settings.perm.manualOverride":     "Mark as granted manually",
    "settings.perm.manualOverride.sub": "Use this if you already granted Full Disk Access in System Settings but Lume doesn't recognize it (happens with unsigned apps).",
    "settings.maint.title":      "Maintenance Mode",
    "settings.maint.locked":     "Locked. The admin password will be requested on the first task that needs it.",
    "settings.maint.unlocked":   "Unlocked. You won't need to type the admin password again in this session.",
    "settings.maint.unlock":     "Unlock",
    "settings.maint.lock":       "Lock",
    "settings.perm.desktop":    "Desktop Folder",
    "settings.perm.documents":  "Documents Folder",
    "settings.perm.downloads":  "Downloads Folder",
    "settings.perm.spaceLens.sub":"Required for Space Lens",
    "settings.general.info":    "When hidden from the Dock, the app is accessible only via the menu bar icon. Click it to reopen the main window.",
    "settings.language.applyHint":"Language changes apply immediately.",

    "donate.popup.title":     "Support Lume for Mac",
    "donate.popup.tagline":   "100% free — but your help makes a difference",
    "donate.popup.intro":     "Lume is developed by a single person, with dedication and care. If it helped you free up space or speed up your Mac, please consider donating — any amount goes a long way!",
    "donate.popup.keyTitle":  "Enter donor key",
    "donate.popup.keyIntro":  "After donating, send proof to hasen.borges@gmail.com. You will receive a key to permanently disable this reminder.",
    "donate.popup.keySuccess":"Valid key! Reminders disabled. Thank you!",
    "donate.popup.validate":  "Validate",
    "donate.popup.invalid":   "Invalid key. Check and try again.",
    "donate.popup.placeholder":"Paste the key here…",
    "donate.popup.alreadyDonated":"I've donated",
    "donate.popup.hide":      "Hide",
    "donate.popup.remindLater":"Remind me later",
    "donate.popup.support":   "I want to support!",
    "donate.popup.copied":    "Copied!",
    "donate.popup.copy":      "Copy",
]

private let esStrings: [String: String] = [
    "sidebar.dashboard":   "Dashboard",
    "sidebar.memory":      "Memoria",
    "sidebar.disk":        "Disco",
    "sidebar.spaceLens":   "Space Lens",
    "sidebar.protection":  "Protección",
    "sidebar.apps":        "Aplicaciones",
    "sidebar.performance": "Rendimiento",
    "sidebar.settings":    "Configuración",
    "sidebar.healthy":     "Sistema saludable",
    "sidebar.health":      "Salud del Mac",
    "sidebar.health.good": "Buena",
    "sidebar.health.attention": "Atención",

    "page.dashboard.title":     "Smart Scan",
    "page.dashboard.subtitle":  "Diagnóstico completo de tu Mac",
    "page.memory.title":        "Limpieza de Memoria",
    "page.memory.subtitle":     "Libera RAM retenida por procesos inactivos",
    "page.disk.title":          "Limpieza de Disco",
    "page.disk.subtitle":       "Elimina cachés, logs y archivos innecesarios",
    "page.spaceLens.title":     "Space Lens",
    "page.spaceLens.subtitle":  "Archivos grandes por disco",
    "page.protection.title":    "Protección",
    "page.protection.subtitle": "Detecta y elimina malware, adware y apps no deseadas",
    "page.apps.title":          "Aplicaciones",
    "page.apps.subtitle":       "Gestiona y desinstala aplicaciones",
    "page.performance.title":   "Rendimiento",
    "page.performance.subtitle":"Optimizaciones y mantenimiento del sistema",

    "common.analyze":   "Analizar",
    "common.analyzing": "Analizando…",
    "common.cancel":    "Cancelar",
    "common.apply":     "Aplicar",
    "common.close":     "Cerrar",
    "common.copy":      "Copiar",
    "common.copied":    "¡Copiado!",
    "common.clean":     "Limpiar",
    "common.delete":    "Eliminar",
    "common.open":      "Abrir",
    "common.refresh":   "Actualizar",
    "common.loading":   "Cargando…",
    "common.search":    "Buscar…",
    "common.execute":   "Ejecutar",
    "common.running":   "Ejecutando…",
    "common.done":      "Listo",
    "common.scan":      "Escanear ahora",
    "common.scanning":  "Escaneando…",
    "common.checking":  "Comprobando…",
    "common.rescan":    "Volver a escanear",
    "common.remove":    "Quitar",
    "common.removing":  "Quitando…",
    "common.confirm":   "Confirmar",
    "common.moveToTrash":"Mover a la Papelera",

    "memory.title":        "Limpieza de Memoria",
    "memory.subtitle":     "Libera RAM retenida en procesos inactivos",
    "memory.cleanBtn":     "Liberar Memoria",
    "memory.cleaning":     "Liberando memoria…",
    "memory.success":      "¡Memoria optimizada!",
    "memory.ramUsed":      "RAM en uso",
    "memory.ramFree":      "RAM libre",
    "memory.topProcesses": "Procesos con mayor consumo",

    "disk.scanBtn":     "Analizar Disco",
    "disk.cleanBtn":    "Limpiar Seleccionados",
    "disk.junkFound":   "encontrados",
    "disk.cleaning":    "Limpiando…",
    "disk.freed":       "¡liberados!",
    "disk.empty":       "¡Tu Mac está limpio!",
    "disk.details":     "Ver detalles",

    "spaceLens.allDisks":   "Todos los Discos",
    "spaceLens.minSize":    "Mín:",
    "spaceLens.all":        "Todos",
    "spaceLens.empty":      "Haz clic en \"Analizar\" para encontrar archivos grandes",
    "spaceLens.noResults":  "No se encontraron archivos grandes",
    "spaceLens.tryLower":   "Prueba reducir el tamaño mínimo",
    "spaceLens.found":      "elementos grandes encontrados",
    "spaceLens.selected":   "seleccionados",
    "spaceLens.name":       "Nombre",
    "spaceLens.type":       "Tipo",
    "spaceLens.disk":       "Disco",
    "spaceLens.size":       "Tamaño",

    "protection.scanBtn":   "Escanear ahora",
    "protection.scanning":  "Escaneando tu Mac…",
    "protection.clean":     "¡Mac Protegido!",
    "protection.threats":   "Amenaza(s) Encontrada(s)",
    "protection.lastScan":  "Último Escaneo",
    "protection.never":     "Nunca",
    "protection.active":    "Activa",
    "protection.quarantine":"Cuarentena",
    "protection.fdaNeeded": "Acceso completo al disco recomendado",
    "protection.fdaWhy":    "Sin este permiso el escaneo estará limitado.",
    "protection.fdaBtn":    "Conceder Acceso",
    "protection.threatList":"Amenazas Detectadas",
    "protection.removeSel": "Eliminar Seleccionados",

    "apps.search":       "Buscar apps…",
    "apps.sortBy":       "Ordenar:",
    "apps.sort.name":    "Nombre",
    "apps.sort.size":    "Tamaño",
    "apps.sort.lastUsed":"Último uso",
    "apps.count":        "apps",
    "apps.empty":        "No se encontraron apps",
    "apps.loading":      "Cargando aplicaciones…",
    "apps.remove":       "Quitar",
    "apps.app":          "Aplicación",
    "apps.version":      "Versión",
    "apps.lastUsed":     "Último Uso",
    "apps.size":         "Tamaño",
    "apps.today":        "Hoy",

    "perf.tasksHeader":   "Tareas de Mantenimiento",
    "perf.loginItems":    "Elementos de Inicio",
    "perf.launchAgents":  "Launch Agents",
    "perf.loginManage":   "Gestionar",
    "perf.openSettings":  "Abrir en Configuración",
    "perf.spotlight":     "Reindexar Spotlight",
    "perf.spotlightDesc": "Resuelve problemas de búsqueda lenta",
    "perf.refresh":       "Actualizar lista",
    "perf.loadingItems":  "Cargando elementos…",
    "perf.noItems":       "No se encontraron elementos",
    "perf.enable":        "Activar",
    "perf.disable":       "Desactivar",
    "perf.remove":        "Eliminar",

    "settings.title":            "Configuración",
    "settings.general":          "General",
    "settings.language":         "Idioma",
    "settings.updates":          "Actualizaciones",
    "settings.donate":           "Donación",
    "settings.behavior":         "Comportamiento de la App",
    "settings.launchAtLogin":    "Iniciar con el sistema",
    "settings.launchAtLogin.sub":"Lume se abre automáticamente al encender tu Mac",
    "settings.hideFromDock":     "Quitar del Dock",
    "settings.hideFromDock.sub": "Mantiene Lume sólo en la barra de menús superior",
    "settings.language.title":   "Idioma de la Interfaz",
    "settings.language.note":    "Selecciona un idioma y haz clic en \"Aplicar\".",
    "settings.language.apply":   "Aplicar idioma",
    "settings.language.applied": "¡Idioma aplicado!",
    "settings.donate.header":    "Apoyar el Desarrollo",
    "settings.donate.intro":     "Lume es 100% gratis y siempre lo será. Si te ayudó, considera donar.",
    "settings.donate.keyHeader": "Clave de Donante",
    "settings.donate.thanks":    "¡Muchas gracias por tu apoyo!",
    "settings.permissions":      "Permisos del Sistema",
    "settings.perm.fda":         "Acceso completo al disco",
    "settings.perm.fda.sub":     "Necesario para la pestaña Protección",
    "settings.perm.granted":     "Concedido",
    "settings.perm.pending":     "Pendiente",

    "menu.healthy":   "Sistema saludable",
    "menu.openLume":  "Abrir Lume",
    "menu.quitLume":  "Salir",
    "menu.diskFree":  "libres en disco",
    "menu.cleanRAM":  "Liberar Memoria",
    "menu.quickScan": "Análisis Rápido de Basura",
    "menu.findJunk":  "Encuentra archivos innecesarios",
    "menu.appName":   "Lume for Mac",

    "dash.cleanup.title":   "Limpieza Inteligente",
    "dash.cleanup.startScan":"Iniciar Análisis",
    "dash.cleanup.intro":   "Haz clic en \"Iniciar Análisis\" para encontrar cachés, logs y archivos innecesarios que ocupan espacio en tu Mac.",
    "dash.cleanup.selected":"Seleccionado para eliminar",
    "dash.cleanup.newScan": "Nuevo análisis",
    "dash.cleanup.cleanNow":"Limpiar Ahora",

    "disk.total":          "Total",
    "disk.categories":     "Categorías de Basura",
    "disk.empty.click":    "Haz clic en \"Analizar\" para encontrar archivos innecesarios",
    "disk.selected":       "Seleccionado",
    "disk.recommended":    "Recomendado",
    "disk.recommendedDesc":"Podemos eliminar de forma segura hasta %@. No afectará el funcionamiento de tu Mac.",
    "disk.details.title":  "Detalles de Archivos",
    "disk.details.sub":    "Archivos a eliminar por categoría",
    "disk.cat.systemCache":    "Caché del Sistema",
    "disk.cat.logs":           "Logs",
    "disk.cat.temp":           "Archivos Temporales",
    "disk.cat.oldDownloads":   "Descargas de +30 días",
    "disk.cat.orphanedSupport":"Restos de Apps Desinstaladas",
    "disk.cat.trash":          "Papelera",
    "disk.cat.xcodeSims":      "Simuladores de Xcode",
    "disk.status.idle":     "Listo para analizar",
    "disk.status.scanning": "Analizando disco…",
    "disk.status.found":    "%@ de basura encontrados",
    "disk.status.clean":    "¡Tu Mac está limpio!",
    "disk.status.freed":    "✓ ¡%@ liberados!",
    "disk.status.nothing":  "No se eliminó nada.",

    "spaceLens.scanning":  "Analizando archivos…",
    "spaceLens.minHint":   "Prueba reducir el tamaño mínimo (actualmente %d MB)",
    "spaceLens.moveTo":    "Mover %d a la Papelera",
    "spaceLens.confirm":   "Esto moverá %d archivo(s) a la Papelera. Podrás restaurarlos si es necesario.",
    "spaceLens.kind.folder":   "Carpeta",
    "spaceLens.kind.video":    "Video",
    "spaceLens.kind.image":    "Imagen",
    "spaceLens.kind.archive":  "Comprimido",
    "spaceLens.kind.document": "Documento",
    "spaceLens.kind.app":      "Aplicación",
    "spaceLens.kind.other":    "Otro",

    "memory.usedOf":     "de %@ usados",
    "memory.detail":     "Uso Detallado",
    "memory.history":    "Historial de RAM (2 min)",
    "memory.topMem":     "Procesos por Memoria",
    "memory.process":    "Proceso",
    "memory.pid":        "PID",
    "memory.ram":        "RAM",

    "sysmon.cpu": "CPU",
    "sysmon.ram": "RAM",

    "protection.scanningText":  "Escaneando tu Mac…",
    "protection.dbUpdated":     "Base de datos actualizada",
    "protection.coverage":      "Escanea LaunchAgents, Daemons, Applications y extensiones de Chrome/Firefox",
    "protection.macClean":      "¡Tu Mac está limpio!",
    "protection.noThreats":     "No se encontraron malware, adware o apps no deseadas.",
    "protection.threat.adware":      "Adware",
    "protection.threat.pup":         "App No Deseada",
    "protection.threat.malware":     "Malware",
    "protection.threat.launchAgent": "Launch Agent Sospechoso",
    "protection.threat.extension":   "Extensión Sospechosa",
    "protection.confirmTitle":  "¿Eliminar Seleccionados?",
    "protection.confirmMsg":    "Esto moverá %d amenaza(s) a la Papelera.",
    "protection.threat.adware.desc":     "Inyecta anuncios y altera el navegador",
    "protection.threat.malware.desc":    "Troyanos y spyware conocidos en macOS",
    "protection.threat.pup.desc":        "Programas que muestran alertas falsas",
    "protection.threat.extension.desc":  "Extensiones de navegador sospechosas",
    "protection.threat.pup.short":       "Apps No Deseadas",
    "protection.threat.extension.short": "Extensiones Sospechosas",

    "apps.confirmTitle": "¿Desinstalar aplicaciones?",
    "apps.confirmMsg":   "Esto moverá %d app(s) (%@) y sus archivos de soporte a la Papelera.",
    "apps.removing":     "Quitando…",
    "apps.removeCount":  "Quitar %d (%@)",
    "apps.openInFinder": "Mostrar en Finder",

    "perf.spotlight.title":       "Reindexar Spotlight",
    "perf.spotlight.desc":        "Reconstruye el índice de búsqueda",
    "perf.spotlight.help":        "Útil cuando Spotlight devuelve resultados incorrectos o incompletos. El proceso tarda unos minutos.",
    "perf.spotlight.btn":         "Reindexar Spotlight",
    "perf.spotlight.running":     "Reindexando…",
    "perf.spotlight.success":     "✓ ¡Reindex iniciado! Tarda unos minutos.",
    "perf.spotlight.failure":     "⚠ No se pudo reindexar. Prueba por Terminal: sudo mdutil -E /",
    "perf.task.dnsCache.name":    "Vaciar Caché DNS",
    "perf.task.dnsCache.desc":    "Resuelve problemas de DNS lento",
    "perf.task.permissions.name":"Reparar Permisos",
    "perf.task.permissions.desc":"Corrige permisos del directorio home",
    "perf.task.fontCache.name":  "Limpiar Caché de Fuentes",
    "perf.task.fontCache.desc":  "Elimina caché de fuentes corruptas",
    "perf.task.trash.name":      "Vaciar Papelera",
    "perf.task.trash.desc":      "Elimina definitivamente los archivos de la papelera",

    "settings.donate.copy":      "Copiar",
    "settings.donate.copied":    "¡Copiado al portapapeles!",
    "settings.donate.pix":       "Brasil",
    "settings.donate.paypal":    "Internacional",
    "settings.donate.keyRandom":"Clave aleatoria",
    "settings.donate.keyEmail":  "Correo",
    "settings.donate.confirmed":"¡Donación confirmada!",
    "settings.donate.confirmedSub":"Recordatorios desactivados. ¡Gracias!",
    "settings.donate.keyIntro": "Después de donar, envía el comprobante a hasen.borges@gmail.com. Recibirás una clave exclusiva para desactivar los recordatorios.",
    "settings.donate.keySuccess":"¡Clave válida! ¡Gracias por tu apoyo!",
    "settings.donate.validate": "Validar",
    "settings.donate.invalid":  "Clave inválida. Verifica e inténtalo de nuevo.",
    "settings.donate.placeholder":"Pega tu clave aquí…",

    "settings.updates.header":   "Información del Software",
    "settings.updates.compat":   "Compatible con Intel y Apple Silicon",
    "settings.updates.upToDate":"Actualizado",
    "settings.updates.check":    "Buscar Actualizaciones",
    "settings.updates.note":     "Las actualizaciones automáticas vía Sparkle estarán disponibles pronto.",

    "settings.perm.openPrivacy":"Abrir Privacidad y Seguridad",
    "settings.perm.fda.full":   "Requerido para la pestaña Protección y análisis completo",
    "settings.perm.fda.coverage":"Este único permiso cubre Escritorio, Documentos, Descargas, Música, Imágenes, Películas y los archivos del sistema que usa Protección. No necesitarás aprobar cada carpeta individualmente.",
    "settings.perm.manualOverride":     "Marcar como concedido manualmente",
    "settings.perm.manualOverride.sub": "Úsalo si ya concediste Acceso Completo al Disco en Configuración pero Lume no lo reconoce (pasa con apps sin firma de desarrollador).",
    "settings.maint.title":      "Modo Mantenimiento",
    "settings.maint.locked":     "Bloqueado. La contraseña de administrador se solicitará en la primera tarea que la necesite.",
    "settings.maint.unlocked":   "Desbloqueado. No necesitarás escribir la contraseña de administrador otra vez en esta sesión.",
    "settings.maint.unlock":     "Desbloquear",
    "settings.maint.lock":       "Bloquear",
    "settings.perm.desktop":    "Carpeta Escritorio",
    "settings.perm.documents":  "Carpeta Documentos",
    "settings.perm.downloads":  "Carpeta Descargas",
    "settings.perm.spaceLens.sub":"Requerido para Space Lens",
    "settings.general.info":    "Al ocultarse del Dock, la app sólo se accede por el icono de la barra de menús. Haz clic ahí para abrir la ventana.",
    "settings.language.applyHint":"Los cambios de idioma se aplican de inmediato.",

    "donate.popup.title":     "Apoya Lume for Mac",
    "donate.popup.tagline":   "100% gratis — pero tu ayuda hace la diferencia",
    "donate.popup.intro":     "Lume es desarrollado por una sola persona, con dedicación. Si te ayudó a liberar espacio o acelerar tu Mac, considera donar — ¡cualquier monto ayuda mucho!",
    "donate.popup.keyTitle":  "Ingresar clave de donante",
    "donate.popup.keyIntro":  "Después de donar, envía el comprobante a hasen.borges@gmail.com. Recibirás una clave para desactivar permanentemente este recordatorio.",
    "donate.popup.keySuccess":"¡Clave válida! Recordatorios desactivados. ¡Gracias!",
    "donate.popup.validate":  "Validar",
    "donate.popup.invalid":   "Clave inválida. Verifica e inténtalo de nuevo.",
    "donate.popup.placeholder":"Pega la clave aquí…",
    "donate.popup.alreadyDonated":"Ya doné",
    "donate.popup.hide":      "Ocultar",
    "donate.popup.remindLater":"Recordarme luego",
    "donate.popup.support":   "¡Quiero Apoyar!",
    "donate.popup.copied":    "¡Copiado!",
    "donate.popup.copy":      "Copiar",
]
